# Generated by Django 2.0.3 on 2018-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overhaul', '0003_devicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='under',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
