# Generated by Django 2.0.3 on 2018-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overhaul', '0004_auto_20180408_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='under',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
