# Generated by Django 2.0.3 on 2018-04-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overhaul', '0005_auto_20180408_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='under',
            field=models.CharField(max_length=20),
        ),
    ]
