# Generated by Django 2.0.3 on 2018-04-12 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overhaul', '0007_devicemodel_repair_is'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoTaskEndModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('is_over', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-crdate'],
            },
        ),
        migrations.CreateModel(
            name='DoTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='overhaul.TaskModel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-crdate'],
            },
        ),
        migrations.AddField(
            model_name='dotaskendmodel',
            name='dotask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='overhaul.DoTaskModel'),
        ),
    ]
