# Generated by Django 2.0.3 on 2018-04-14 16:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overhaul', '0011_auto_20180414_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
