# Generated by Django 2.0.3 on 2018-04-15 14:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overhaul', '0012_auto_20180414_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
