# Generated by Django 2.0.3 on 2018-04-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overhaul', '0013_auto_20180415_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='MessagesModel',
        ),
    ]
